services:
  - type: web
    name: healthmatrix
    env: node
    rootDir: .
    buildCommand: npm install --prefix backend && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: npm --prefix backend start
    autoDeploy: true
